# Generated by Django 3.0.4 on 2020-06-06 17:28

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtitle',
            name='text',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='subtitles',
            field=models.ManyToManyField(related_name='flashcards', to='users.Subtitle'),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='media/subs'), upload_to=''),
        ),
        migrations.AddField(
            model_name='subtitle',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='learnt',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='difficulty',
            field=models.FloatField(default=7.7),
        ),
    ]
