# Generated by Django 3.0.4 on 2020-06-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200606_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='learnt',
            field=models.FloatField(default=0.0),
        ),
    ]
