# Generated by Django 3.0.4 on 2020-06-06 19:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200606_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.jpeg', storage=django.core.files.storage.FileSystemStorage(location='media/profile_pics'), upload_to=''),
        ),
    ]
